AllCops:
  TargetRubyVersion: 2.5
  DisplayStyleGuide: true
  Include:
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true


Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Layout/AlignParameters:
  Enabled: Yes

Metrics/MethodLength:
  Max: 30
  Enabled: false

Style/Tab:
  Enabled: false

Style/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 4

Style/SingleLineMethods:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EndOfLine:
  EnforcedStyle: lf

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false