development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  host: localhost
  username: <%= ENV['PS_USERNAME'] %>
  password: <%= ENV['PS_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  host: localhost
  username: <%= ENV['PS_USERNAME'] %>
  password: <%= ENV['PS_PASSWORD'] %>
